name: Build Spring Boot App from Subdirectory

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v3

    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'

    - name: Build with Maven (from demo folder)
      run: mvn clean package -f demo/pom.xml

    - name: Run Tests
      run: mvn test -f demo/pom.xml
